---
title: "個人開発者の教養"
summary: "アイディア出しから、実装・集客などについてまとめた個人開発者のための本です。"
topics: ["markdown", "zenn"]
published: false
price: 3500
---
chapters:
  - about
  - create-idea
  - update-book
  - conclusion
